apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-green
  namespace: zero-downtime
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      color: green
  template:
    metadata:
      labels:
        app: myapp
        color: green
    spec:
      terminationGracePeriodSeconds: 15
      containers:
        - name: app
          image: nakib200108/zero-downtime:v2
          ports:
            - containerPort: 8080
          env:
            - name: VERSION
              value: "v2"
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","sleep 5"]
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            periodSeconds: 2
            initialDelaySeconds: 1
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
